name: weathermate
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_dotenv: ^2.1.0
  geolocator: ^6.0.0
  http: ^0.12.2
  flutter_spinkit: ^4.1.2
  simple_animations: ^2.2.2
  supercharged: ^1.10.0
  geocoder: ^0.2.1
  basic_utils: ^1.2.0
  time_formatter: ^1.0.0
  rflutter_alert: ^1.0.3
  pull_to_refresh: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  - .env

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900
  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat-Regular.ttf